name: Claude Code Assistant
on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  claude-assistant:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'issues' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Claude Code Action Official
        uses: anthropics/claude-code-action@beta
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}